### ISSUE TITLE
Assignments Feedback

### ISSUE THREAD

**Issue by a-wilkes** [unmeshvrije/python-for-beginners#1]
### Iterable Class
- Not sure when discussion of classes/objects is planned in the syllabus, but some understanding of the basics would probably be required before tackling this slightly more complex example.
- Also, I'm not sure what the purpose of the 'start' and 'stop' arguments are - it seems to me that once the instruction 'start' is given, unless the class is multithreaded, passing 'stop' will not be possible until the 'start' instruction is already finished.
    - Perhaps 'start', 'step' and some kind of 'go to n' instruction make more sense.

### Decorators
- Along with the iterators, I get the impression that these topics might require a bit more understanding from the students than the others - maybe leaving them for the more advanced students is best?

### Functional Programming Basics
- I think these would be well suited to the end of the first week after the students have seen non-functional functions first
    - If discussion of lambdas is not directly planned, perhaps questions about this topic can be left for the advanced students again?

### Remainder
- The rest of the questions all seem fairly simple, which is good - I think almost all of them could be attempted by every student without too many issues

**Comment by unmeshvrije** [comment]
Iterable class : I think @a-wilkes  misunderstood the question. range() function in Python accepts three parameters (arguments), start, stop (end) and step.
E.g range(1,10) will return numbers from 1 to 9 (used in for loops in Python)
range(10) will return numbers from 0 to 9 (be default start = 0)
range (1,10,2) would return 1,3,5,7,9 (because the step is 2)

I agree that assignments for Decorators and functional programming should be left for advanced students, I will cover Decorators more in detail. Functional programming less so.
